In [1]:
import pandas as pd
import numpy as np
import seaborn as sns
import xgboost as xgb
import matplotlib.pyplot as plt
%matplotlib inline
import warnings
warnings.filterwarnings('ignore')
from sklearn import ensemble,metrics,cross_validation,preprocessing,grid_search
path='C:/Projects/Hackerearth_2/'
from catboost import CatBoost, CatBoostClassifier
import lightgbm as lgb

C:\Users\sharm_000\Anaconda2\envs\py36\lib\site-packages\sklearn\cross_validation.py:44: DeprecationWarning: This module was deprecated in version 0.18 in favor of the model_selection module into which all the refactored classes and functions are moved. Also note that the interface of the new CV iterators are different from that of this module. This module will be removed in 0.20.
  "This module will be removed in 0.20.", DeprecationWarning)


In [2]:
data=pd.read_csv(path+'train.csv',dtype={'roadId':object})
labels=pd.read_csv(path+'labels.csv',dtype={'roadId':object})
test_data=pd.read_csv(path+'test.csv',dtype={'roadId':object})
print (data.shape,labels.shape)
len(np.unique(data['roadId'])),len(np.unique(test_data['roadId']))

(28914, 14) (4825, 3)


(4825, 400)

In [3]:
data.head()

roadId   totalLaneLines   laneLineId  \
0  3177248677                3  X3177248677   
1  3177248677                3  13177248677   
2  3177248677                3  23177248677   
3  3177248676                9  X3177248676   
4  3177248676                9  13177248676   

                                 laneLineCoordinates   totalLinesOnLeft  \
0   11.117636626741222 49.43799310961545|11.11761...                  2   
1   11.11771009862968 49.43794191822495|11.117697...                  0   
2   11.117673197144772 49.43796782435575|11.11765...                  1   
3   11.11742645905593 49.437419830658655|11.11740...                  3   
4   11.117117406584201 49.43662220739599|11.11710...                  1   

    totalLaneLinesOnRight  distFromLaneLineOnLeft  distFromLaneLineOnRight  \
0                       0             3.863433276                            
1                       2                                      3.740901458   
2                       1             3.740901458              3.863433276   
3                       5             4.634520764              1.727115052   
4                       7             5.783676541              1.727115052   

    laneLineLength   roadLength   noOfIntersectingLaneLinesLeft  \
0         4.396337    40.570710                               0   
1        37.316844    40.570710                               0   
2        40.365319    40.570710                               0   
3        18.177112   207.655745                               0   
4        95.552747   207.655745                               0   

    noOfIntersectingLaneLinesRight  isIntersectingWithRoadGeometry  \
0                                0                           false   
1                                0                           false   
2                                0                            true   
3                                0                           false   
4                                0                           false   

    roadCategory  
0              2  
1              2  
2              2  
3              2  
4              2

In [4]:
new_data=pd.merge(data,labels,on='roadId',how='left')
new_data.columns=[i.strip(' ')for i in new_data.columns]
new_data['roadCoordinates_count']=new_data['roadCoordinates'].apply(lambda x: len(x.split()))
new_data['laneLineCoordinates_count']=new_data['laneLineCoordinates'].apply(lambda x: len(x.split()))
new_data=new_data.fillna(0)
new_data.head(2)

roadId  totalLaneLines   laneLineId  \
0  3177248677               3  X3177248677   
1  3177248677               3  13177248677   

                                 laneLineCoordinates  totalLinesOnLeft  \
0   11.117636626741222 49.43799310961545|11.11761...                 2   
1   11.11771009862968 49.43794191822495|11.117697...                 0   

   totalLaneLinesOnRight distFromLaneLineOnLeft distFromLaneLineOnRight  \
0                      0            3.863433276                           
1                      2                                    3.740901458   

   laneLineLength  roadLength  noOfIntersectingLaneLinesLeft  \
0        4.396337    40.57071                              0   
1       37.316844    40.57071                              0   

   noOfIntersectingLaneLinesRight isIntersectingWithRoadGeometry  \
0                               0                          false   
1                               0                          false   

   roadCategory                                    roadCoordinates  noOfLanes  \
0             2   11.11747 49.43763|11.11753 49.43776|11.11761 ...          2   
1             2   11.11747 49.43763|11.11753 49.43776|11.11761 ...          2   

   roadCoordinates_count  laneLineCoordinates_count  
0                      5                          3  
1                      5                          6

In [59]:
def num_con(x):
    try:
        return float(x)
    except:
        return 0
    
def geom(x):
    if x=='false':
        return 0
    else:
        return 1

In [60]:
new_data['distFromLaneLineOnLeft']=new_data['distFromLaneLineOnLeft'].apply(lambda x: num_con(x))
new_data['distFromLaneLineOnRight']=new_data['distFromLaneLineOnRight'].apply(lambda x: num_con(x))
new_data['isIntersectingWithRoadGeometry']=new_data['isIntersectingWithRoadGeometry'].apply(lambda x: num_con(x))

In [61]:
new_data.columns

Index(['roadId', 'totalLaneLines', 'laneLineId', 'laneLineCoordinates',
       'totalLinesOnLeft', 'totalLaneLinesOnRight', 'distFromLaneLineOnLeft',
       'distFromLaneLineOnRight', 'laneLineLength', 'roadLength',
       'noOfIntersectingLaneLinesLeft', 'noOfIntersectingLaneLinesRight',
       'isIntersectingWithRoadGeometry', 'roadCategory', 'roadCoordinates',
       'noOfLanes', 'roadCoordinates_count', 'laneLineCoordinates_count'],
      dtype='object')

In [62]:
train_pro_data=new_data.groupby(by='roadId').agg({'laneLineId':'nunique','totalLaneLines':'mean','distFromLaneLineOnRight':'mean',\
                                   'distFromLaneLineOnLeft':'mean','laneLineLength':'mean',\
                                  'roadLength':'mean','noOfIntersectingLaneLinesLeft':'mean',\
                                  'roadCategory':'mean','isIntersectingWithRoadGeometry':'mean',\
                                  'laneLineCoordinates_count':'mean','noOfLanes':'mean'}).reset_index()

In [63]:
def laneLineLength_cut(x):
    if x <25:
        return 'A'
    elif x <50:
        return 'B'
    elif x <200:
        return 'C'
    elif x <250:
        return 'D'
    else:
        return 'E'

In [64]:
train_pro_data['roadLength_bucket']=train_pro_data['roadLength'].apply(lambda x: laneLineLength_cut(x))

In [65]:
lbl2=preprocessing.LabelEncoder()
train_pro_data['roadLength_bucket']=lbl2.fit_transform(train_pro_data['roadLength_bucket'])

In [66]:
train_pro_data['noOfLanes']=train_pro_data['noOfLanes'].apply(lambda x:str(x))

In [67]:
lbl=preprocessing.LabelEncoder()
lbl.fit(train_pro_data['noOfLanes'])

LabelEncoder()

In [68]:
train_pro_data['noOfLanes']=lbl.transform(train_pro_data['noOfLanes'])

In [69]:
train_pro_data.shape

(4825, 13)

In [70]:
# new_test_data=pd.merge(test_data,labels,on='roadId',how='left')
test_data.columns=[i.strip(' ')for i in test_data.columns]
test_data.shape,len(np.unique(test_data['roadId']))

((2493, 14), 400)

In [71]:
test_data.head()

roadId  totalLaneLines  laneLineId  \
0  291531296               5  X291531296   
1  291531296               5  1291531296   
2  291531296               5  2291531296   
3  291531296               5  3291531296   
4  291531296               5  4291531296   

                                 laneLineCoordinates  totalLinesOnLeft  \
0   11.329899604343693 43.72956824243773|11.33004...                 2   
1   11.329900151795446 43.729503478051974|11.3300...                 4   
2   11.329899913660833 43.72953696742431|11.33004...                 3   
3   11.329899175813209 43.72961906004278|11.33004...                 1   
4   11.329899073264464 43.729650480155186|11.3300...                 0   

   totalLaneLinesOnRight distFromLaneLineOnLeft distFromLaneLineOnRight  \
0                      2            5.655398294              3.49899823   
1                      0            3.685959755                           
2                      1             3.49899823             3.685959755   
3                      3            3.481580911             5.655398294   
4                      4                                    3.481580911   

   laneLineLength  roadLength  noOfIntersectingLaneLinesLeft  \
0       12.054597   12.056004                              0   
1       12.060141   12.056004                              0   
2       12.052468   12.056004                              0   
3       12.046642   12.056004                              0   
4       12.054345   12.056004                              0   

   noOfIntersectingLaneLinesRight isIntersectingWithRoadGeometry  roadCategory  
0                               0                          false             1  
1                               0                          false             1  
2                               0                          false             1  
3                               0                          false             1  
4                               0                          false             1

In [72]:
# new_test_data['roadCoordinates_count']=new_test_data['roadCoordinates'].apply(lambda x: len(x.split()))
test_data['laneLineCoordinates_count']=test_data['laneLineCoordinates'].apply(lambda x: len(x.split()))
test_data=test_data.fillna(0)
print (test_data.shape)
test_data.head(2)

(2493, 15)


roadId  totalLaneLines  laneLineId  \
0  291531296               5  X291531296   
1  291531296               5  1291531296   

                                 laneLineCoordinates  totalLinesOnLeft  \
0   11.329899604343693 43.72956824243773|11.33004...                 2   
1   11.329900151795446 43.729503478051974|11.3300...                 4   

   totalLaneLinesOnRight distFromLaneLineOnLeft distFromLaneLineOnRight  \
0                      2            5.655398294              3.49899823   
1                      0            3.685959755                           

   laneLineLength  roadLength  noOfIntersectingLaneLinesLeft  \
0       12.054597   12.056004                              0   
1       12.060141   12.056004                              0   

   noOfIntersectingLaneLinesRight isIntersectingWithRoadGeometry  \
0                               0                          false   
1                               0                          false   

   roadCategory  laneLineCoordinates_count  
0             1                          3  
1             1                          3

In [73]:
test_data['distFromLaneLineOnLeft']=test_data['distFromLaneLineOnLeft'].apply(lambda x: num_con(x))
test_data['distFromLaneLineOnRight']=test_data['distFromLaneLineOnRight'].apply(lambda x: num_con(x))
test_data['isIntersectingWithRoadGeometry']=test_data['isIntersectingWithRoadGeometry'].apply(lambda x: num_con(x))

In [74]:
test_pro_data=test_data.groupby(by='roadId').agg({'laneLineId':'nunique','totalLaneLines':'mean','distFromLaneLineOnRight':'mean',\
                                   'distFromLaneLineOnLeft':'mean','laneLineLength':'mean',\
                                  'roadLength':'mean','noOfIntersectingLaneLinesLeft':'sum',\
                                  'roadCategory':'mean','isIntersectingWithRoadGeometry':'sum',\
                                  'laneLineCoordinates_count':'mean'}).reset_index()

In [75]:
test_pro_data.shape

(400, 11)

In [76]:
test_pro_data['roadLength_bucket']=test_pro_data['roadLength'].apply(lambda x: laneLineLength_cut(x))
test_pro_data['roadLength_bucket']=lbl2.transform(test_pro_data['roadLength_bucket'])

In [77]:
test_pro_data.columns

Index(['roadId', 'laneLineId', 'totalLaneLines', 'distFromLaneLineOnRight',
       'distFromLaneLineOnLeft', 'laneLineLength', 'roadLength',
       'noOfIntersectingLaneLinesLeft', 'roadCategory',
       'isIntersectingWithRoadGeometry', 'laneLineCoordinates_count',
       'roadLength_bucket'],
      dtype='object')

In [78]:
train_pro_data.columns

Index(['roadId', 'laneLineId', 'totalLaneLines', 'distFromLaneLineOnRight',
       'distFromLaneLineOnLeft', 'laneLineLength', 'roadLength',
       'noOfIntersectingLaneLinesLeft', 'roadCategory',
       'isIntersectingWithRoadGeometry', 'laneLineCoordinates_count',
       'noOfLanes', 'roadLength_bucket'],
      dtype='object')

In [79]:
X=test_pro_data.columns.tolist()[1:]
Y='noOfLanes'

### XGB .773

In [80]:
dtrain=xgb.DMatrix(train_pro_data[X],label=train_pro_data[Y])
dtest=xgb.DMatrix(test_pro_data[X])

In [81]:
def score_f1(preds,dtrain):
#     print ('>>>>',type(preds),preds.shape)
    labels=dtrain.get_label()
    return 'score_f1',metrics.f1_score(labels,preds,average='weighted')

In [82]:
param={}
param['eta']=.3
param['objective']='multi:softmax'
param['num_class']=6
param['max_depth']= 12
param['n_estimators']: 350

In [83]:
xcv=xgb.cv(param,dtrain,num_boost_round=200,feval=score_f1,maximize=True,early_stopping_rounds=50,\
       show_stdv=False,verbose_eval=10)

[0]	train-score_f1:0.795749	test-score_f1:0.52096
[10]	train-score_f1:0.967383	test-score_f1:0.540661
[20]	train-score_f1:0.99002	test-score_f1:0.544128
[30]	train-score_f1:0.996983	test-score_f1:0.5392
[40]	train-score_f1:0.999482	test-score_f1:0.541166
[50]	train-score_f1:0.999896	test-score_f1:0.540253
[60]	train-score_f1:1	test-score_f1:0.539296
[70]	train-score_f1:1	test-score_f1:0.538467


In [84]:
num_rounds=len(xcv)
num_rounds

22

In [85]:
watchlist=[(dtrain,'dtrain')]
model_xgb=xgb.train(param,dtrain,evals=watchlist,num_boost_round=num_rounds,feval=score_f1,maximize=True,\
                    early_stopping_rounds=50,\
       verbose_eval=10)

[0]	dtrain-score_f1:0.780648
Will train until dtrain-score_f1 hasn't improved in 50 rounds.
[10]	dtrain-score_f1:0.952099
[20]	dtrain-score_f1:0.979741


In [86]:
model_pred=model_xgb.predict(dtest)
np.unique(model_pred,return_counts=True)

(array([ 0.,  1.,  2.,  3.,  4.,  5.], dtype=float32),
 array([ 26, 212, 104,  54,   3,   1], dtype=int64))

In [87]:
model_pred=lbl.inverse_transform(model_pred.astype(int))
np.unique(model_pred)

array(['1', '2', '3', '4', '5', '6'], dtype=object)

In [88]:
sub_samp1=pd.DataFrame(test_pro_data['roadId'])
sub_samp1['noOfLanes']=model_pred

In [89]:
sub_samp1.to_csv(path+'2xgb_model_less_feature.csv',index=False)

In [90]:
train_X,test_X,train_y,test_y=cross_validation.train_test_split(train_pro_data[X],train_pro_data[Y],test_size=.3,random_state =123)
train_X.shape,train_y.shape,test_X.shape,test_y.shape

((3377, 11), (3377,), (1448, 11), (1448,))

### Catboost

In [91]:
clf = CatBoostClassifier(learning_rate=0.01, iterations=1000, random_seed=0, \
                          loss_function='MultiClass', class_count=6)
clf.fit(train_X, train_y,eval_set=(test_X,test_y),use_best_model=True)

In [92]:
metrics.f1_score(test_y,np.ravel(clf.predict(test_X)),average='weighted')

0.54433440217152729

In [93]:
# clf.fit(train_pro_data[X], train_pro_data[Y])
pred_cat=np.ravel(clf.predict(test_pro_data[X]))

np.unique(pred_cat,return_counts=True)

(array([ 0.,  1.,  2.,  3.,  4.]),
 array([ 22, 214, 134,  29,   1], dtype=int64))

In [94]:
pred_cat=lbl.inverse_transform(pred_cat.astype(int))
print(np.unique(pred_cat))

sub_samp2=pd.DataFrame(test_pro_data['roadId'])
sub_samp2['noOfLanes']=pred_cat

sub_samp2.to_csv(path+'2cat_model_less_feature.csv',index=False)

['1' '2' '3' '4' '5']


### lightgbm

In [95]:
t4_params = {
    'boosting_type': 'gbdt', 'objective': 'multiclass', 'nthread': -1, 'silent': True,
    'num_leaves': 2**4, 'learning_rate': 0.05, 'max_depth': 4,
    'max_bin': 255, 'subsample_for_bin': 50000,
    'subsample': 0.8, 'subsample_freq': 1, 'colsample_bytree': 0.6, 'reg_alpha': 1, 'reg_lambda': 0,
    'min_split_gain': 0.5, 'min_child_weight': 1, 'min_child_samples': 10, 'scale_pos_weight': 1}

# they can be used directly to build a LGBMClassifier (which is wrapped in a sklearn fashion)

In [96]:
ligh_mdl=lgb.LGBMClassifier(**t4_params)

In [97]:
ligh_mdl.fit(train_X, train_y)

LGBMClassifier(boosting_type='gbdt', colsample_bytree=0.6, learning_rate=0.05,
        max_bin=255, max_depth=4, min_child_samples=10, min_child_weight=1,
        min_split_gain=0.5, n_estimators=10, nthread=-1, num_leaves=16,
        objective='multiclass', reg_alpha=1, reg_lambda=0,
        scale_pos_weight=1, seed=0, silent=True, subsample=0.8,
        subsample_for_bin=50000, subsample_freq=1)

In [98]:
metrics.f1_score(test_y,ligh_mdl.predict(test_X),average='weighted')

0.50741036287931585

In [99]:
ligh_mdl.fit(train_pro_data[X], train_pro_data[Y])
pred_lgb=ligh_mdl.predict(test_pro_data[X])
np.unique(pred_lgb,return_counts=True)

(array([0, 1, 2, 3, 4], dtype=int64),
 array([ 12, 188, 174,  21,   5], dtype=int64))

In [100]:
pred_lgb=lbl.inverse_transform(pred_lgb.astype(int))
print(np.unique(pred_lgb))

sub_samp3=pd.DataFrame(test_pro_data['roadId'])
sub_samp3['noOfLanes']=pred_lgb

sub_samp3.to_csv(path+'2lgb_model_less_feature.csv',index=False)

['1' '2' '3' '4' '5']


In [101]:
lolwa=pd.DataFrame(data={'roadId':test_pro_data['roadId'],'xgb':model_pred,'cat':pred_cat,'lgb':pred_lgb})

In [102]:
def mode_data(x,y,z):
    if x==y:
        return x
    elif y==z:
        return y
    else:
        return 'lala'

In [103]:
lolwa['ense']=lolwa[['xgb','cat','lgb']].apply(lambda x: mode_data(*x),axis=1)

In [104]:
def val_repl(x,y):
    if x=='lala':
        return y
    else:
        return x

In [105]:
lolwa['ense']=lolwa[['ense','xgb']].apply(lambda x: val_repl(*x),axis=1)

In [106]:
lolwa=lolwa[['roadId','ense']]
lolwa.columns=['roadId','noOfLanes']

In [107]:
np.unique(lolwa['noOfLanes'],return_counts=True)

(array(['1', '2', '3', '4', '5', '6'], dtype=object),
 array([ 17, 210, 137,  31,   4,   1], dtype=int64))

In [108]:
lolwa.to_csv('2ense_xcl.csv',index=False)